"""practice sessions and virtual rounds

Revision ID: 6dbab0f48375
Revises: 9c1f4e7a2b83
Create Date: 2026-08-15 21:27:39.849844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6dbab0f48375'
down_revision: Union[str, Sequence[str], None] = '9c1f4e7a2b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_session_user_id'), 'practice_session', ['user_id'], unique=False)
    op.create_table('virtual_round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('home_tee_hero', 'e6', 'gspro', 'other', name='simplatform'), nullable=False),
    sa.Column('course_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('holes_played', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_round_user_id'), 'virtual_round', ['user_id'], unique=False)
    op.create_table('practice_shot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('club', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('club_speed_mph', sa.Float(), nullable=True),
    sa.Column('ball_speed_mph', sa.Float(), nullable=True),
    sa.Column('smash_factor', sa.Float(), nullable=True),
    sa.Column('launch_angle_deg', sa.Float(), nullable=True),
    sa.Column('spin_rate_rpm', sa.Float(), nullable=True),
    sa.Column('spin_axis_deg', sa.Float(), nullable=True),
    sa.Column('club_path_deg', sa.Float(), nullable=True),
    sa.Column('face_angle_deg', sa.Float(), nullable=True),
    sa.Column('carry_yards', sa.Float(), nullable=True),
    sa.Column('total_yards', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['practice_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_shot_club'), 'practice_shot', ['club'], unique=False)
    op.create_index(op.f('ix_practice_shot_session_id'), 'practice_shot', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_shot_session_id'), table_name='practice_shot')
    op.drop_index(op.f('ix_practice_shot_club'), table_name='practice_shot')
    op.drop_table('practice_shot')
    op.drop_index(op.f('ix_virtual_round_user_id'), table_name='virtual_round')
    op.drop_table('virtual_round')
    op.drop_index(op.f('ix_practice_session_user_id'), table_name='practice_session')
    op.drop_table('practice_session')
    # ### end Alembic commands ###
