"""round hole pin

Revision ID: cfdf38640868
Revises: da7ddd5e0023
Create Date: 2026-08-16 15:27:37.362634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'cfdf38640868'
down_revision: Union[str, Sequence[str], None] = 'da7ddd5e0023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('round_hole_pin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('hole_id', sa.Integer(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['hole_id'], ['hole.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'hole_id', name='uq_pin_round_hole')
    )
    # No op.create_index for `location` here: GeoAlchemy2 creates its own
    # GIST spatial index at table-creation time (see CLAUDE.md) — an
    # explicit one here would collide with it.
    op.create_index(op.f('ix_round_hole_pin_hole_id'), 'round_hole_pin', ['hole_id'], unique=False)
    op.create_index(op.f('ix_round_hole_pin_round_id'), 'round_hole_pin', ['round_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_round_hole_pin_round_id'), table_name='round_hole_pin')
    op.drop_index(op.f('ix_round_hole_pin_hole_id'), table_name='round_hole_pin')
    op.drop_table('round_hole_pin')
    # ### end Alembic commands ###
