"""unique shot round hole shot_number

Revision ID: da7ddd5e0023
Revises: a91c4d6e2f57
Create Date: 2026-08-16 06:17:09.950043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da7ddd5e0023'
down_revision: Union[str, Sequence[str], None] = 'a91c4d6e2f57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_shot_round_hole_number', 'shot', ['round_id', 'hole_id', 'shot_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_shot_round_hole_number', 'shot', type_='unique')
    # ### end Alembic commands ###
